name: Deploy Graph

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  deploy-mainnet:
    runs-on: ubuntu-latest
    env:
      GRAPH_SUBGRAPH_ACCOUNT: ${{ github.repository_owner }}
      GRAPH_SUBGRAPH_NAME: givpower-subgraph
      GRAPH_CONFIG_FILE: subgraph.production-mainnet.yaml
      NETWORK_NAME: mainnet
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: $GRAPH_SUBGRAPH_NAME
          graph_account: $GRAPH_SUBGRAPH_ACCOUNT
          graph_config_file: $GRAPH_CONFIG_FILE

  deploy-xdai:
    runs-on: ubuntu-latest
    env:
      GRAPH_SUBGRAPH_ACCOUNT: ${{ github.repository_owner }}
      GRAPH_SUBGRAPH_NAME: giveth-economy-xdai
      GRAPH_CONFIG_FILE: subgraph.production-xdai.yaml
      NETWORK_NAME: xdai
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: $GRAPH_SUBGRAPH_NAME
          graph_account: $GRAPH_SUBGRAPH_ACCOUNT
          graph_config_file: $GRAPH_CONFIG_FILE
