name: Deploy Graph to staging

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      GRAPH_SUBGRAPH_ACCOUNT: ${{ github.repository_owner }}
      GRAPH_SUBGRAPH_NAME: giveth-economy-goerli-staging
      GRAPH_CONFIG_FILE: subgraph.deployment-7-goerli.yaml
      NETWORK_NAME: goerli
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Codegen
        run: yarn codegen:deployment-7:goerli
      - name: Build
        run: yarn build:deployment-7:goerli
      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: $GRAPH_SUBGRAPH_NAME
          graph_account: $GRAPH_SUBGRAPH_ACCOUNT
          graph_config_file: $GRAPH_CONFIG_FILE
