name: Deploy Graph to develop

on:
  push:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Yarn Latest vetsion
        run: yarn set version latest
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  deploy-staging-goerli:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Yarn Latest vetsion
        run: yarn set version latest
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Manifest
        run: yarn generate-manifests
      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: giveth-economy-goerli-staging
          graph_account: giveth
          graph_config_file: subgraph.deployment-7-goerli.yaml

  deploy-staging-gnosis:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Yarn Latest vetsion
        run: yarn set version latest
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Manifest
        run: yarn generate-manifests
      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{ secrets.GRAPH_ACCESS_TOKEN }}
          graph_subgraph_name: giveth-economy-xdai-staging
          graph_account: giveth
          graph_config_file: subgraph.deployment-7-gnosis.yaml
