name: Deploy <main branch> to Graph Studio

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  deploy-mainnet:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Manifest
        run: yarn generate-manifests
      - name: Deploy to Graph Studio
        run: |
          yarn run graph deploy "$SUBGRAPH_NAME" "$CONFIG_FILE" \
            --node https://api.studio.thegraph.com/deploy/ \
            --deploy-key "$DEPLOY_KEY" \
            --version-label "${GITHUB_SHA:0:8}"
        env:
          DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
          SUBGRAPH_NAME: giveth-giveconomy-mainnet
          CONFIG_FILE: subgraph.production-mainnet.yaml

  deploy-gnosis:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Manifest
        run: yarn generate-manifests
      - name: Deploy to Graph Studio
        run: |
          yarn run graph deploy "$SUBGRAPH_NAME" "$CONFIG_FILE" \
            --node https://api.studio.thegraph.com/deploy/ \
            --deploy-key "$DEPLOY_KEY" \
            --version-label "${GITHUB_SHA:0:8}"
        env:
          DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
          SUBGRAPH_NAME: giveth-giveconomy-gnosischain
          CONFIG_FILE: subgraph.production-gnosis.yaml
  
  deploy-optimism:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Manifest
        run: yarn generate-manifests
      - name: Deploy to Graph Studio
        run: |
          yarn run graph deploy "$SUBGRAPH_NAME" "$CONFIG_FILE" \
            --node https://api.studio.thegraph.com/deploy/ \
            --deploy-key "$DEPLOY_KEY" \
            --version-label "${GITHUB_SHA:0:8}"
        env:
          DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
          SUBGRAPH_NAME: giveth-giveconomy-optimism
          CONFIG_FILE: subgraph.production-optimism-mainnet.yaml
